export const GET_LOGIN_STATE = 'GET_LOGIN_STATE';
export const CHANGE_LOGIN_STATE = 'CHANGE_LOGIN_STATE';
export const LOGIN_STATE_LIST = {
    PEDDING: 'PEDDING',
    ONBOARD: 'ONBOARD',
    UNONBOARD: 'UNONBOARD',
    LOGIN: 'LOGIN'
}

